# Generated by Django 4.1.4 on 2022-12-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('seats', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=60)),
                ('vin', models.PositiveIntegerField()),
                ('curr_mileage', models.PositiveIntegerField(help_text='miles')),
                ('service_interval', models.PositiveIntegerField(help_text='miles')),
                ('next_service', models.PositiveIntegerField(help_text='miles')),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
