# Generated by Django 4.1.4 on 2022-12-20 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_car_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='curr_mileage',
            new_name='current_mileage',
        ),
    ]
