# Generated by Django 4.1.4 on 2022-12-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_rename_curr_mileage_car_current_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('length', models.PositiveIntegerField(help_text='feet')),
                ('width', models.PositiveIntegerField(help_text='feet')),
                ('hin', models.CharField(max_length=17)),
                ('current_hours', models.PositiveSmallIntegerField(help_text='miles')),
                ('service_interval', models.PositiveIntegerField(help_text='miles')),
                ('next_service', models.PositiveIntegerField(help_text='miles')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('seats', models.PositiveSmallIntegerField()),
                ('bed_length', models.PositiveIntegerField(help_text='inches')),
                ('color', models.CharField(max_length=60)),
                ('vin', models.CharField(max_length=17)),
                ('current_mileage', models.PositiveIntegerField(help_text='miles')),
                ('service_interval', models.PositiveIntegerField(help_text='miles')),
                ('next_service', models.PositiveIntegerField(help_text='miles')),
            ],
        ),
    ]
