# Generated by Django 4.1.4 on 2022-12-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_boat_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='length',
            field=models.PositiveIntegerField(help_text='inches'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='width',
            field=models.PositiveIntegerField(help_text='inches'),
        ),
    ]
